- hosts: yoloapplication
  become: true
  vars:
    mongodb_volume: yolo_app_data
    backend_db_network: backend_db_network
    backend_frontend_network: backend_frontend_network
    db_container_name: yolo_mongodb
    backend_container_name: yolo_backend
    client_container_name: yolo_frontend
    mongodb_image: mongo
    backend_image: sammwaura/yolo_backend:v1.0.4
    client_image: sammwaura/yolo_frontend:v1.0.4
    app_repo: "https://github.com/samuelmwaura/yolo.git"
    repository_destination: "/home/vagrant/yolo_application"


  roles:
    - initial_server_setup
    - setting_docker
    - Cloning_and_setting_up_app_connections
    - spinning_up_the_containers