- name: Clone application repository into YoloBox
  git:
    repo: "{{ app_repo }}"
    dest: "{{ repository_destination }}"
    version: "master"
    force: yes

- name: Create the backend_db_network
  shell: docker network create {{ backend_db_network }}

- name: Create the backend_frontend_network
  shell: docker network create {{ backend_frontend_network }}

- name: Create the database mongodb_volume
  shell: docker volume create {{ mongodb_volume }}
