apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-frontend
  labels:
    app: yolo-app-frontend.  #Identifier when relating this deployment to other objects
  namespace: yolo-app-kubernetes
spec:
  replicas: 3 #3 instances of the pod will be created
  selector:
    matchLabels:
      app: yolo-app-frontend
    template: #Template for the pods that are being managed
      metadata:
        labels: 
          app: yolo-app-frontend
      spec:
        containers:  #definition of the containers that will run inside the pod
          - name: yolo-app-frontend
            image: gcr.io/yolo-app-kubernetes-project/frontend:v1.0.4
            ports:
              - containerPort: 80. #Port inside the container where the traffic is being directed   